### ISSUE TITLE
모두의 깃 5.2 SSH Key

### ISSUE THREAD

**Issue by mrgirong** [kangtegong/git-for-everyone#1]
깃허브에서 SSH key를 등록하려고 하는데, 책에는 나오지 않는 **Key type**가 **Authentication Key**와 **Signing Key**가 있습니다. 이 둘의 차이를 알고 싶습니다. 어떤것으로 진행해야하나요?

**Comment by kangtegong** [comment]
authentication key가 맞습니다 :)

이는 github에 키를 등록하는 과정에 대해 설명하는 부분에서도 나와 있습니다.

<img width="599" alt="스크린샷 2022-11-05 오후 10 27 06" src="https://user-images.githubusercontent.com/47781146/200122252-6729d9e3-911a-4a07-9b73-0e8748f7d40a.png">
