### ISSUE TITLE
질문있어요!

### ISSUE THREAD

**Issue by yeongdolee** [kangtegong/git-for-everyone#2]
git 스테이지에서 내리는 명령어도 있나요?

**Comment by kangtegong** [comment]
네 있습니다. 스테이지에서 내리는 명령어는 `git restore --staged <스테이지에서 내릴 파일 이름>` 입니다.

어떤 파일을 stage에 올린 뒤 git status를 입력하면 아래와 같이 해당 명령어가 출력됩니다.

```
$ git status
On branch mynew
Your branch is up to date with 'origin/review/python-tracing-v1'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   rank
```

  **(use "git restore --staged <file>..." to unstage)** 부분에 해당합니다.
